// Nội dung Đề cương môn học PRO192 (Spring 2021) — chép nguyên văn từ tài liệu gốc.
// Mỗi ô nhiều dòng dùng ký tự \n, render bằng whitespace-pre-line.

export interface SyllabusTable {
  headers: string[]
  rows: string[][]
}

export interface SyllabusTab {
  id: string
  tabLabel: string
  title: string
  table: SyllabusTable
}

export const syllabusTabs: SyllabusTab[] = [
  {
    id: 'syllabus',
    tabLabel: 'Syllabus',
    title: 'Object-Oriented Programming using Java (PRO192) Syllabus',
    table: {
      headers: ['No', 'Title', 'Details'],
      rows: [
        ['1', 'Document type', 'SYLLABUS'],
        ['2', 'Program', 'UNDERGRADUATE PROGRAM'],
        ['3', 'Decision No.', '1293/QĐ-ĐHFPT dated DD/MM/YYYY'],
        ['4', 'Course Name', 'Object-Oriented Programming using Java'],
        ['5', 'Course Code', 'PRO192'],
        ['6', 'No of credits', '3'],
        ['7', 'Degree Level', 'Bachelor'],
        [
          '8',
          'Time Allocation',
          "Class hours: 30 slots - 1slot = 90'\nLectures: 15 slots\nTutorials: 15 slots\nHome study: 60 slots",
        ],
        ['9', 'Pre-requisite', 'PRF192'],
        [
          '10',
          'Description',
          '- This subject introduces the student to object-oriented programming. The student learns to build reusable objects, encapsulate data and logic within a class, inherit one class from another and implement polymorphism.\n- The student learns basic Java language syntax and semantics and uses this language to implement object-oriented programming principles\n- Adhere to object-oriented programming principles including encapsulation, polymorphism and inheritance when writing program code\n- Trace the execution of Java program logic to determine what a program does or to validate the correctness of a program',
        ],
        [
          '11',
          "Student's task",
          "- Students must attend at least 80% of contact slots in order to be accepted to the final examination.\n- Student is responsible to do all exercises given by instructor in class or at home and submit on time.\n- Use laptop in class only for learning purpose\n- Promptly access to the FU CMS at http://cms.fpt.edu.vn for up-to-date course information",
        ],
        ['12', 'Tools', "Text Book\n'NetBean x.x\nInternet"],
        [
          '13',
          'Assessment scheme',
          "1) On-going Assessment - At least 2 progress tests: 10% - Labs (6): 10% - 1 assignment: 20% - 1 practical exam: 30% 2) Final exam (60'): 30% 3) Final Result: 100% Completion Criteria: 1) Every on-going assessment component > 0 2) Final Exam Score >= 4 & Final Result >= 5",
        ],
        ['14', 'Min GPA to pass', '5'],
        ['15', 'Scoring scale', '10'],
        ['16', 'Approved date', '44167'],
      ],
    },
  },
  {
    id: 'materials',
    tabLabel: 'Materials',
    title: 'Course Materials',
    table: {
      headers: [
        'No',
        'Material Description',
        'Purpose',
        'ISBN',
        'Type',
        'Note',
        'Author',
        'Publisher',
        'Published Date',
        'Edition',
      ],
      rows: [
        ['1', 'Object-Oriented Programming using Java', 'text book', '', 'website', '', '', '', '', ''],
        ['2', 'Core Java Volume I and II- 11th Edition - Cay Horstmann', 'text book', '', '', '', '', '', '', ''],
        [
          '3',
          'Java 8 Specification, docs.oracle.com/javase/specs/jvms/se8/html/jvms-1.html#jvms-1.1',
          'text book',
          '',
          'text book',
          '',
          '',
          '',
          '',
          '',
        ],
        ['4', 'Course slide', '', '', '', '', '', '', '', ''],
        ['5', 'Labs & assignment', '', '', '', '', '', '', '', ''],
      ],
    },
  },
  {
    id: 'learning-outcomes',
    tabLabel: 'Learning Outcomes',
    title: 'Learning Outcomes',
    table: {
      headers: ['No', 'LO Name', 'LO Description', 'Sub.ID', 'Sub.ID Learning outcome'],
      rows: [
        [
          'LO1',
          '',
          'Understand the concepts of object oriented (OO) programs to solve problems and fundamentals of object-oriented programming in Java',
          '',
          '',
        ],
        [
          'LO2',
          '',
          'Practice basic Java language syntax and semantics to write Java programs and use concepts such as variables, conditional and iterative execution methods',
          '',
          '',
        ],
        ['LO3', '', 'Uses streams to read and write data from/to different types of sources/targets', '', ''],
        ['LO4', '', "Discuss the benefits and the use of JAVA's Exceptional handling mechanism", '', ''],
        [
          'LO5',
          '',
          'Identify classes, objects, members of a class and relationships among them needed for a specific problem',
          '',
          '',
        ],
        [
          'LO6',
          '',
          'Explain the concept and demonstrates the use of Polymorphism, Encapsulation, Abstraction and Inheritance in java',
          '',
          '',
        ],
        ['LO7', '', 'Discuss the principles and the use of abstract classes and interfaces in java', '', ''],
        ['LO8', '', 'Understand and implement a complete program using object array', '', ''],
        [
          'LO9',
          '',
          'Explain the principles and the use of some (java collections) abstract data types (list, set, map)',
          '',
          '',
        ],
      ],
    },
  },
  {
    id: 'schedule',
    tabLabel: 'Schedule',
    title: 'Course Schedule',
    table: {
      headers: [
        'Sess.',
        'Content',
        'LO',
        'ITU',
        "Student's materials",
        "Teacher's Material",
        "Student's task",
        "Lecturer's task",
      ],
      rows: [
        [
          '1',
          'Introduction:\n1.1 Welcome to Object-Oriented\n1.2 Object Terminology',
          'LO1',
          'I',
          'Textbook, slides',
          'Textbook, slides',
          '',
          '',
        ],
        [
          '2',
          'Foundations:\n2.1 basic Java language: variable, operators, array and logic instructions',
          'LO2',
          'I,T',
          'Textbook, slides',
          'Textbook, slides',
          '',
          '',
        ],
        [
          '3',
          '2.2 Input and Output (Standard I/O)',
          'LO3',
          'I,T',
          'Textbook, slides',
          'Textbook, slides',
          '',
          '',
        ],
        ['4', 'Lab 1 assistance', 'LO2, LO3', 'U', '', '', '', ''],
      ],
    },
  },
  {
    id: 'grading-structure',
    tabLabel: 'Grading Structure',
    title: 'Grading Structure',
    table: {
      headers: [
        '#',
        'Assessment Component',
        'Assessment Type',
        'Weight',
        'Part',
        'Min value to meet Completion Criteria',
        'Duration',
        'LO',
        'Type of questions',
        'Number of questions',
        'Scope of knowledge and skill of questions',
        'How?',
        'Note',
      ],
      rows: [
        [
          '1',
          'Progress Test',
          'on-going',
          '10%',
          '2',
          '0.00001',
          "30'/each",
          'Test 1: LO1, LO2, LO3\nTest 2: LO4, LO5, LO6',
          'Multiple choices\nMarked by Computer or a suitable format',
          '20/each',
          '',
          'in class, by LMS system',
          'Instruction and schedules for Progress Tests must be presented in the Course Implementation Plan approved by director of the campus.\nProgress test must be taken right after the last lectures of required material.\nInstructor has responsibility to review the test for students after graded.',
        ],
        [
          '2',
          'Assignment',
          'on-going',
          '20%',
          '1',
          '0.00001',
          '28 slots',
          'LO1->LO9',
          '',
          '',
          'All subjects in syllabus',
          'in class, by teacher',
          '',
        ],
        [
          '3',
          'Lab',
          'on-going',
          '10%',
          '6',
          '0.00001',
          "90'/each",
          'LO1->LO9',
          '',
          '',
          '',
          'in class, by teacher',
          '',
        ],
      ],
    },
  },
]
